### PR TITLE
New info about jdk jre jvm

### PR DESCRIPTION
**Pull request by maggan1968**
Screen Shot 2021-08-07 at 2 42 50 PM

### CODE REVIEW

**Review by veneraserik — COMMENTED** [review]
👍👍👍

**Comment by maggan1968** [comment]
Simple explanation from Merwe, perfect!

**Comment by Merweskaa** [comment]
Excellent🤙🏻

**Comment by Merweskaa** [comment]
U can cheat from there🙈🙈

**Comment by maggan1968** [comment]
did you record your self already?

**Review by tmayan — APPROVED** [review]
thanks Margie that was so useful

**Pull request merged**
